# Generated by Django 3.2.7 on 2021-09-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_segmento', models.CharField(max_length=150)),
                ('produto_marca', models.CharField(max_length=150)),
                ('produto_nome', models.CharField(max_length=150)),
                ('produto_descricao', models.TextField(blank=True, null=True)),
                ('produto_voltagem', models.CharField(max_length=15)),
                ('produto_tamanho', models.CharField(max_length=15)),
                ('produto_preço', models.CharField(max_length=15)),
                ('produto_quantidade', models.IntegerField()),
                ('produto_localizacao', models.CharField(max_length=255)),
                ('produto_foto', models.BinaryField()),
            ],
        ),
    ]
