# Generated by Django 3.2.7 on 2021-09-21 05:05

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa_marca', models.CharField(max_length=150)),
                ('cnpj', models.FloatField(verbose_name=django.db.models.constraints.UniqueConstraint)),
            ],
        ),
        migrations.RenameField(
            model_name='segmentos',
            old_name='produto_localizacao',
            new_name='descricao_segmento',
        ),
        migrations.RenameField(
            model_name='segmentos',
            old_name='produto_marca',
            new_name='segmento',
        ),
        migrations.RemoveField(
            model_name='segmentos',
            name='produto_descricao',
        ),
        migrations.RemoveField(
            model_name='segmentos',
            name='produto_foto',
        ),
        migrations.RemoveField(
            model_name='segmentos',
            name='produto_nome',
        ),
        migrations.RemoveField(
            model_name='segmentos',
            name='produto_preço',
        ),
        migrations.RemoveField(
            model_name='segmentos',
            name='produto_quantidade',
        ),
        migrations.RemoveField(
            model_name='segmentos',
            name='produto_segmento',
        ),
        migrations.RemoveField(
            model_name='segmentos',
            name='produto_tamanho',
        ),
        migrations.RemoveField(
            model_name='segmentos',
            name='produto_voltagem',
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento_produto_models', models.CharField(max_length=150)),
                ('produto', models.CharField(max_length=150)),
                ('produto_nome', models.CharField(max_length=150)),
                ('produto_descricao', models.TextField(blank=True, null=True)),
                ('produto_voltagem', models.CharField(max_length=15)),
                ('produto_tamanho', models.CharField(max_length=15)),
                ('produto_preço', models.CharField(max_length=15)),
                ('produto_quantidade', models.IntegerField()),
                ('produto_foto', models.FileField(upload_to='')),
                ('produto_marca_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marcas')),
            ],
        ),
        migrations.AddField(
            model_name='marcas',
            name='segmento_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.segmentos'),
        ),
    ]
