# Generated by Django 3.2.7 on 2021-09-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='imagem',
        ),
    ]
